version: '2'
services:
  master:
    image: malfurionpd/jmeter-master
    stdin_open: true
    network_mode: host
    tty: true
    ports:
    - 60000:60000/tcp
  slave01:
    image: malfurionpd/jmeter-slave
    depends_on: master
    stdin_open: true
    tty: true
    ports:
    - 10991:1099/tcp
    - 50001:50000/tcp

  slave02:
    image: malfurionpd/jmeter-slave
    depends_on: master
    stdin_open: true
    tty: true
    ports:
    - 10992:1099/tcp
    - 50002:50000/tcp